# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

workflows:
  default-workflow:
    name: Default Workflow
    environment:
      vars:
        BUILD_VERSION: 1${BUILD_NUMBER}BETA
        APP_PASSWORD_ENV_VARIABLE: Josias4528
      flutter: dev
      xcode: latest
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: '[dev]'
          include: true
          source: false
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build apk --profile --build-name=1.0.${BUILD_NUMBER}
      - |
        #!/usr/bin/env sh

         set -e # exit on first failed commandset
         set -x # print all executed commands to the log

         if [ "$FCI_BUILD_STEP_STATUS" == "success" ]
         then
           new_version=v$BUILD_VERSION
           git tag $new_version
           git push "https://DevelopTestGithub:$APP_PASSWORD_ENV_VARIABLE@github.com/DevelopTestGithub/test7" --tags
         fi
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - jipina_est@utmachala.edu.ec
